# Generated by Django 3.2.13 on 2022-05-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_rm_unused_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('contact_username', models.CharField(blank=True, max_length=32, null=True)),
                ('contact_first_name', models.CharField(max_length=256)),
                ('contact_last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('tg_user', models.ManyToManyField(to='tgbot.User')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_message', models.TextField()),
                ('contact_id', models.ManyToManyField(to='tgbot.Contact')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
