# Generated by Django 3.2.13 on 2022-05-07 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_auto_20220504_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='tg_user',
        ),
    ]
