# Generated by Django 3.2.13 on 2022-05-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_remove_contact_tg_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tg_user',
            field=models.PositiveBigIntegerField(default=False),
        ),
    ]
