# Generated by Django 3.2.13 on 2022-05-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0011_auto_20220508_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='username',
        ),
    ]
