# Generated by Django 3.2.13 on 2022-05-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0012_remove_contact_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tg_user',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
