# Generated by Django 3.2.13 on 2022-05-08 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0013_contact_tg_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='tg_user',
        ),
    ]
