# Generated by Django 3.2.13 on 2022-05-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0014_remove_contact_tg_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='contact_id',
        ),
        migrations.AddField(
            model_name='contact',
            name='id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
