# Generated by Django 3.2.13 on 2022-05-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0015_auto_20220508_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
